[NotebookApp | ERROR] Exception while loading config file /etc/jupyter/nbgrader_config.py
    Traceback (most recent call last):
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/etc/jupyter/nbgrader_config.py", line 29
        "C++14": "// your code here\nthrow new Error();"
               ^
    SyntaxError: invalid syntax
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] nteract extension loaded from /home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/nteract_on_jupyter
[NotebookApp | INFO] Serving notebooks from local directory: /home/hp/workfolder/Practical-ML-on-H2O
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://localhost:8888/?token=6ecbd79d447eb4e239a1bcef3d41cd945f4717e315b3eddb
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=6ecbd79d447eb4e239a1bcef3d41cd945f4717e315b3eddb
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from 127.0.0.1
[NotebookApp | INFO] Creating new notebook in 
[NotebookApp | INFO] Kernel started: fb3c503d-fb55-46ab-9bb5-e24f8284ef15
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel fb3c503d-fb55-46ab-9bb5-e24f8284ef15
[NotebookApp | INFO] Saving file at /Week 1 - A quick deep learning overview.ipynb
[NotebookApp | INFO] Saving file at /Week 1 - A quick deep learning overview.ipynb
[NotebookApp | INFO] Saving file at /Week 1 - A quick deep learning overview.ipynb
[NotebookApp | INFO] Saving file at /Week 1 - A quick deep learning overview.ipynb
[NotebookApp | INFO] Saving file at /Week 1 - A quick deep learning overview.ipynb
[NotebookApp | INFO] Saving file at /Week 1 - A quick deep learning overview.ipynb
[NotebookApp | INFO] Saving file at /Week 1 - A quick deep learning overview.ipynb
[NotebookApp | INFO] Saving file at /Week 1 - A quick deep learning overview.ipynb
[NotebookApp | INFO] Saving file at /Week 1 - A quick deep learning overview.ipynb
[NotebookApp | INFO] Creating new notebook in 
[NotebookApp | INFO] Kernel started: 7c0a5ddb-abb5-4e6b-b158-536be9f65538
[NotebookApp | INFO] Starting buffering for fb3c503d-fb55-46ab-9bb5-e24f8284ef15:1fa2cd8723ea4bce9727b623ce822f56
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 7c0a5ddb-abb5-4e6b-b158-536be9f65538
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel fb3c503d-fb55-46ab-9bb5-e24f8284ef15
[NotebookApp | INFO] Saving file at /AutoML H2O.ipynb
[NotebookApp | INFO] Saving file at /AutoML H2O.ipynb
[NotebookApp | INFO] Saving file at /AutoML H2O.ipynb
[NotebookApp | INFO] Saving file at /AutoML H2O.ipynb
[NotebookApp | INFO] Starting buffering for 7c0a5ddb-abb5-4e6b-b158-536be9f65538:c60c7d7084384e5db0216763cb4d14f0
[NotebookApp | INFO] Kernel shutdown: 7c0a5ddb-abb5-4e6b-b158-536be9f65538
[NotebookApp | INFO] Kernel shutdown: fb3c503d-fb55-46ab-9bb5-e24f8284ef15
[NotebookApp | WARNING] Got events for closed stream None
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down 0 kernels
[NotebookApp | ERROR] Exception while loading config file /etc/jupyter/nbgrader_config.py
    Traceback (most recent call last):
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/etc/jupyter/nbgrader_config.py", line 29
        "C++14": "// your code here\nthrow new Error();"
               ^
    SyntaxError: invalid syntax
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] nteract extension loaded from /home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/nteract_on_jupyter
[NotebookApp | INFO] Serving notebooks from local directory: /home/hp/workfolder/Practical-ML-on-H2O
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://localhost:8888/?token=b161883f553b9355be16b25aa9dc43f3fc0934bd4a2d3f2c
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=b161883f553b9355be16b25aa9dc43f3fc0934bd4a2d3f2c
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from 127.0.0.1
[NotebookApp | INFO] Kernel started: 8234e122-c2bd-44df-a09b-a077c37e3f0f
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 8234e122-c2bd-44df-a09b-a077c37e3f0f
[NotebookApp | INFO] Starting buffering for 8234e122-c2bd-44df-a09b-a077c37e3f0f:b578cc2cd8064e6a811e4a0712ad6165
[NotebookApp | WARNING] Notebook Week3_PR_Template.ipynb is not trusted
[NotebookApp | WARNING] delete /Week3_PR_Template.ipynb
[NotebookApp | INFO] Copying Week 1 - A quick deep learning overview.ipynb to 
[NotebookApp | INFO] Kernel started: 32298ac8-6562-4353-91f8-73dd4ea3df64
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 32298ac8-6562-4353-91f8-73dd4ea3df64
[NotebookApp | INFO] Saving file at /Week 2 - Random Forest.ipynb
[NotebookApp | INFO] Saving file at /Week 2 - Random Forest.ipynb
[NotebookApp | INFO] Saving file at /Week 2 - Random Forest.ipynb
[NotebookApp | INFO] Copying Week 2 - Random Forest.ipynb to 
[NotebookApp | INFO] Starting buffering for 32298ac8-6562-4353-91f8-73dd4ea3df64:2fe8be496f05424b9529d47e2e80253b
[NotebookApp | INFO] Kernel started: aeb02e51-8458-4eb3-a218-e90569c64b2e
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel aeb02e51-8458-4eb3-a218-e90569c64b2e
[NotebookApp | INFO] Saving file at /Week 2 - GBM.ipynb
[NotebookApp | INFO] Saving file at /Week 2 - GBM.ipynb
[NotebookApp | INFO] Starting buffering for aeb02e51-8458-4eb3-a218-e90569c64b2e:75def00d2eb84d5a861fb5291f8f694b
[NotebookApp | INFO] Kernel shutdown: 8234e122-c2bd-44df-a09b-a077c37e3f0f
[NotebookApp | INFO] Kernel shutdown: 32298ac8-6562-4353-91f8-73dd4ea3df64
[NotebookApp | INFO] Kernel shutdown: aeb02e51-8458-4eb3-a218-e90569c64b2e
[NotebookApp | INFO] Creating new notebook in 
[NotebookApp | INFO] Kernel started: 98fd598d-7078-4c2a-a53f-b175e9fb65e9
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 98fd598d-7078-4c2a-a53f-b175e9fb65e9
[NotebookApp | INFO] Saving file at /Week 2 - Data from client.ipynb
[NotebookApp | INFO] Saving file at /Week 2 - Data from client.ipynb
[NotebookApp | INFO] Saving file at /Week 2 - Data from client.ipynb
[NotebookApp | INFO] Saving file at /Week 2 - Data from client.ipynb
[NotebookApp | INFO] Saving file at /Week 2 - Data from client.ipynb
[NotebookApp | INFO] Starting buffering for 98fd598d-7078-4c2a-a53f-b175e9fb65e9:fce5f85980ee468f9e1641bbea10f9ee
[NotebookApp | INFO] Kernel shutdown: 98fd598d-7078-4c2a-a53f-b175e9fb65e9
[NotebookApp | INFO] Creating new notebook in 
[NotebookApp | INFO] Kernel started: 9dfad96c-da34-409c-87a8-9f8cf828e6de
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 9dfad96c-da34-409c-87a8-9f8cf828e6de
[NotebookApp | INFO] Saving file at /Week 2 - Artificial Data Sets.ipynb
[NotebookApp | INFO] Starting buffering for 9dfad96c-da34-409c-87a8-9f8cf828e6de:04dd66e9272a4f4ca721ea1ed06b0379
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 9dfad96c-da34-409c-87a8-9f8cf828e6de
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down 1 kernel
[NotebookApp | INFO] Kernel shutdown: 9dfad96c-da34-409c-87a8-9f8cf828e6de
[NotebookApp | ERROR] Exception while loading config file /etc/jupyter/nbgrader_config.py
    Traceback (most recent call last):
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/etc/jupyter/nbgrader_config.py", line 29
        "C++14": "// your code here\nthrow new Error();"
               ^
    SyntaxError: invalid syntax
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] nteract extension loaded from /home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/nteract_on_jupyter
[NotebookApp | INFO] Serving notebooks from local directory: /home/hp/workfolder/Practical-ML-on-H2O
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://localhost:8888/?token=22dd3df4b4364b4f80ec3044e9334879a7fc9c450dc1d851
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=22dd3df4b4364b4f80ec3044e9334879a7fc9c450dc1d851
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from 127.0.0.1
[NotebookApp | INFO] Kernel started: e29aae2f-93ac-49c9-80df-a98f7f5ffd29
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel e29aae2f-93ac-49c9-80df-a98f7f5ffd29
[NotebookApp | INFO] Saving file at /Week 2 - Artificial Data Sets.ipynb
[NotebookApp | INFO] Saving file at /Week 2 - Artificial Data Sets.ipynb
[NotebookApp | INFO] Saving file at /Week 2 - Artificial Data Sets.ipynb
[NotebookApp | INFO] Saving file at /Week 2 - Artificial Data Sets.ipynb
[NotebookApp | INFO] Saving file at /Week 2 - Artificial Data Sets.ipynb
[NotebookApp | INFO] Saving file at /Week 2 - Artificial Data Sets.ipynb
[NotebookApp | INFO] Saving file at /Week 2 - Artificial Data Sets.ipynb
[NotebookApp | INFO] Saving file at /Week 2 - Artificial Data Sets.ipynb
[NotebookApp | INFO] Starting buffering for e29aae2f-93ac-49c9-80df-a98f7f5ffd29:8150d81a26a747c28c670c14e690c089
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down 1 kernel
[NotebookApp | INFO] Kernel shutdown: e29aae2f-93ac-49c9-80df-a98f7f5ffd29
[NotebookApp | ERROR] Exception while loading config file /etc/jupyter/nbgrader_config.py
    Traceback (most recent call last):
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/etc/jupyter/nbgrader_config.py", line 29
        "C++14": "// your code here\nthrow new Error();"
               ^
    SyntaxError: invalid syntax
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] nteract extension loaded from /home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/nteract_on_jupyter
[NotebookApp | INFO] Serving notebooks from local directory: /home/hp/workfolder/Practical-ML-on-H2O
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://localhost:8888/?token=4dbcdcad45f1e56f29a47417d25c3b10c015769921cfd675
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=4dbcdcad45f1e56f29a47417d25c3b10c015769921cfd675
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from 127.0.0.1
[NotebookApp | INFO] Kernel started: 3574b606-9c29-4899-80cd-cf98b83d7e22
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 3574b606-9c29-4899-80cd-cf98b83d7e22
[NotebookApp | INFO] Saving file at /Week 2 - Artificial Data Sets.ipynb
[NotebookApp | INFO] Saving file at /Week 2 - Artificial Data Sets.ipynb
[NotebookApp | INFO] Saving file at /Week 2 - Artificial Data Sets.ipynb
[NotebookApp | INFO] Saving file at /Week 2 - Artificial Data Sets.ipynb
